CREATE TABLE users (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(600) NOT NULL,
	birthdate DATE NOT NULL,
	isActivated boolean DEFAULT false	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;