CREATE TABLE users (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	sexo ENUM('0','1') NOT NULL,
	password VARCHAR(600) NOT NULL,
	birthdate DATE NOT NULL,
	rua VARCHAR(100) NOT NULL,
	numero VARCHAR(10) NOT NULL,
	bairro VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	cep VARCHAR(12) NOT NULL,
	estado VARCHAR(30) NOT NULL,
	complemento VARCHAR(150) NOT NULL,
	activated boolean DEFAULT false	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;