CREATE TABLE activation_token (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT(20) NOT NULL,
	token VARCHAR(600) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;